const products = [
  { id: 1, name: 'Low arc pitcher', category: 'Stoneware · Oat', price: 58, tag: 'New', image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=850&q=85' },
  { id: 2, name: 'Morrow taper set', category: 'Beeswax · Clay', price: 24, tag: 'Restocked', image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=850&q=85' },
  { id: 3, name: 'Field notes no. 3', category: 'Paper · 80 pages', price: 16, tag: '', image: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=850&q=85' },
  { id: 4, name: 'Sunday table cloth', category: 'Linen · Undyed', price: 82, tag: 'Limited', image: 'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=1300&q=85' },
  { id: 5, name: 'Dawn cup', category: 'Stoneware · Moss', price: 32, tag: '', image: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=850&q=85' },
  { id: 6, name: 'Brass wick trimmer', category: 'Solid brass', price: 28, tag: '', image: 'https://images.unsplash.com/photo-1602607205645-22ce93ba4b2d?auto=format&fit=crop&w=850&q=85' }
];
let cart = [];
const $ = (selector) => document.querySelector(selector);
const grid = $('#product-grid');
grid.innerHTML = products.map(product => `<article class="product"><div class="product-media"><img src="${product.image}" alt="${product.name}" />${product.tag ? `<span class="product-tag">${product.tag}</span>` : ''}<button class="add-button" aria-label="Add ${product.name} to bag" data-id="${product.id}">+</button></div><div class="product-info"><div><h3>${product.name}</h3><span>${product.category}</span></div><p>$${product.price}</p></div></article>`).join('');
const scrim = $('#scrim'), cartPanel = $('#cart-panel'), authPanel = $('#auth-panel'), toast = $('#toast');
function closePanels(){scrim.classList.remove('visible');cartPanel.classList.remove('open');authPanel.classList.remove('open');cartPanel.setAttribute('aria-hidden','true');authPanel.setAttribute('aria-hidden','true')}
function openPanel(panel){closePanels();scrim.classList.add('visible');panel.classList.add('open');panel.setAttribute('aria-hidden','false')}
$('#open-cart').onclick = () => openPanel(cartPanel); $('#open-auth').onclick = () => openPanel(authPanel); scrim.onclick = closePanels; document.querySelectorAll('[data-close]').forEach(button => button.onclick = closePanels);
function renderCart(){const count = cart.reduce((sum,item) => sum + item.quantity, 0);document.querySelectorAll('.cart-count').forEach(el=>el.textContent=count);$('#panel-count').textContent=`(${count})`;const items=$('#cart-items'), footer=$('#cart-footer');if(!cart.length){items.innerHTML='<div class="empty-cart"><span class="roundel">MG</span><h2>Your bag is waiting.</h2><p>Add a little something from the collection.</p><button class="underlined" data-close>Continue shopping</button></div>';items.querySelector('[data-close]').onclick=closePanels;footer.hidden=true;return}items.innerHTML=cart.map(item=>`<div class="cart-row"><img src="${item.image}" alt="${item.name}"/><div><h3>${item.name}</h3><p>$${item.price}.00</p><div class="quantity"><button aria-label="Remove one ${item.name}" data-change="-1" data-id="${item.id}">−</button><span>${item.quantity}</span><button aria-label="Add one ${item.name}" data-change="1" data-id="${item.id}">+</button></div></div><button aria-label="Remove ${item.name}" data-remove="${item.id}">×</button></div>`).join('');footer.hidden=false;$('#subtotal').textContent=`$${cart.reduce((sum,item)=>sum+item.price*item.quantity,0)}.00`;items.querySelectorAll('[data-change]').forEach(button=>button.onclick=()=>changeQuantity(+button.dataset.id,+button.dataset.change));items.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{cart=cart.filter(item=>item.id!==+button.dataset.remove);renderCart()})}
function changeQuantity(id,delta){const item=cart.find(entry=>entry.id===id);item.quantity+=delta;if(item.quantity===0)cart=cart.filter(entry=>entry.id!==id);renderCart()}
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
grid.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(!button)return;const product=products.find(p=>p.id===+button.dataset.id),existing=cart.find(item=>item.id===product.id);if(existing)existing.quantity++;else cart.push({...product,quantity:1});renderCart();showToast(`${product.name} added to your bag`)});
$('#google-signin').onclick=()=>{closePanels();showToast('Google sign-in is ready for your integration.')};$('#email-signin').onclick=()=>{closePanels();showToast('You’re signed in — demo mode.')};$('.checkout-button').onclick=()=>showToast('Checkout is a mock interaction.');renderCart();
